---
title: "Minimal Example"
author: "Ben Baumer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Minimal Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Install packages

```{r, eval=FALSE, message=FALSE}
install.packages("devtools")
devtools::install_github("beanumber/etl")
devtools::install_github("beanumber/airlines")
```

## Load packages

```{r, message=FALSE}
require(dplyr)
require(etl)
require(airlines)
```

## Create the airlines database

```{r, eval=FALSE}
library(RMySQL)
# must have pre-existing database "airlines"
db <- src_mysql(host = "localhost", user = "r-user", password = "mypass", dbname = "airlines")
```

Instantiate the `etl` object

```{r, eval=FALSE}
airlines <- etl("airlines", db, dir = "~/dumps/airlines")
```

Initialize the database

```{r, eval=FALSE}
library(magrittr)
airlines %<>%
  etl_create(year = 1987)
```

Once the database is set up, you can update the flights table with more data.  

```{r, eval=FALSE}
lapply(1988:2015, etl_update, obj = airlines)
```

Verify that the data seems accurate.

```{r, eval=FALSE}
flights <- db %>%
  tbl(from = "flights")
flights %>%
  summarise(numFlights = n())
```

This should return about 163 million flights from October 1987 to June 2015. 

```{r, eval=FALSE}
flights %>%
  filter(year > 2013) %>%
  group_by(year) %>%
  summarise(numMonths = count(distinct(month)), numFlights = n())
```